project_id = "mykdpfqpvuvrhbomzvpe"

[functions.healthmax-triage]
verify_jwt = false

[functions.medicine-search]
verify_jwt = false

[functions.medicine-import]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.twilio-whatsapp]
verify_jwt = false
